
package Views;

import ViewModels.ControladorAlumno;
import ViewModels.ControladorDocente;

/**
 *
 * @author ¡Diego Andres Salas!
 */
public class Colegio extends javax.swing.JFrame {

    /**
     * Creates new form Colegio
     */
    public Colegio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoDocente = new javax.swing.ButtonGroup();
        btngrupoAlumno = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LOGO1 = new javax.swing.JLabel();
        tpanDocente2 = new javax.swing.JTabbedPane();
        jpnDocente = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tpanDocente1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCodigoAlumno4 = new javax.swing.JLabel();
        txtCodigoDocente = new javax.swing.JTextField();
        lblNombreAlumno4 = new javax.swing.JLabel();
        txtNombreDocente = new javax.swing.JTextField();
        txtApellidoDocente = new javax.swing.JTextField();
        lblApellidoAlumno4 = new javax.swing.JLabel();
        lblNidAlumno6 = new javax.swing.JLabel();
        txtNidDocente = new javax.swing.JTextField();
        lblGeneroAlumno2 = new javax.swing.JLabel();
        lblFehcaNacAlumno2 = new javax.swing.JLabel();
        DateDocente = new com.toedter.calendar.JDateChooser();
        txtDireccionDocente = new javax.swing.JTextField();
        lblCodigoAlumno5 = new javax.swing.JLabel();
        txtEdadDocente = new javax.swing.JTextField();
        lblNombreAlumno5 = new javax.swing.JLabel();
        txtEmailDocente = new javax.swing.JTextField();
        txtTelefonoDocente = new javax.swing.JTextField();
        lblApellidoAlumno5 = new javax.swing.JLabel();
        lblNidAlumno7 = new javax.swing.JLabel();
        btnAgregarDocente = new javax.swing.JButton();
        btnBorrarDocente = new javax.swing.JButton();
        btnActualizarDocente = new javax.swing.JButton();
        btnSeleccionarDocente = new javax.swing.JButton();
        cbxGenero = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDocente = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblBuscarDocente = new javax.swing.JLabel();
        txtBuscarDocente = new javax.swing.JTextField();
        jpnAlumno = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscarAlumno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        tpanAlumno1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCodigoAlumno = new javax.swing.JLabel();
        txtCodigoAlumn = new javax.swing.JTextField();
        lblNombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        lblApellidoAlumno = new javax.swing.JLabel();
        lblNidAlumno = new javax.swing.JLabel();
        txtNidAlumno = new javax.swing.JTextField();
        lblGeneroAlumno = new javax.swing.JLabel();
        lblFehcaNacAlumno = new javax.swing.JLabel();
        DateAlumno = new com.toedter.calendar.JDateChooser();
        txtDirecciondAlumno = new javax.swing.JTextField();
        lblCodigoAlumno1 = new javax.swing.JLabel();
        txtEdaAlumn = new javax.swing.JTextField();
        lblNombreAlumno1 = new javax.swing.JLabel();
        txtEmailAlumno = new javax.swing.JTextField();
        txtTelefonoAlumno = new javax.swing.JTextField();
        lblApellidoAlumno1 = new javax.swing.JLabel();
        lblNidAlumno1 = new javax.swing.JLabel();
        lblNidAlumno2 = new javax.swing.JLabel();
        txtGradoAlumno = new javax.swing.JTextField();
        btnAgregarAlumno = new javax.swing.JButton();
        btnBorrarAlumno = new javax.swing.JButton();
        btnSeleccionarAlumno = new javax.swing.JButton();
        btnActualizaAlumno = new javax.swing.JButton();
        cbxGeneroAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jpnNota = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblBuscar1 = new javax.swing.JLabel();
        txtBuscarNotas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tpanAlumno4 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblCodigoAlumno8 = new javax.swing.JLabel();
        txtCodigoAlumn3 = new javax.swing.JTextField();
        lblNombreAlumno8 = new javax.swing.JLabel();
        txtNombreAlumno3 = new javax.swing.JTextField();
        txtApellidoAlumno3 = new javax.swing.JTextField();
        lblApellidoAlumno8 = new javax.swing.JLabel();
        lblNidAlumno11 = new javax.swing.JLabel();
        txtNidAlumno3 = new javax.swing.JTextField();
        lblGeneroAlumno4 = new javax.swing.JLabel();
        rbtnGeneroMasAlumno4 = new javax.swing.JRadioButton();
        rbtnGeneroFemAlumno4 = new javax.swing.JRadioButton();
        lblFehcaNacAlumno4 = new javax.swing.JLabel();
        DateAlumno4 = new com.toedter.calendar.JDateChooser();
        txtDirecciondAlumno4 = new javax.swing.JTextField();
        lblCodigoAlumno9 = new javax.swing.JLabel();
        txtEdaAlumn4 = new javax.swing.JTextField();
        lblNombreAlumno9 = new javax.swing.JLabel();
        txtEmailAlumno4 = new javax.swing.JTextField();
        txtTelefonoAlumno4 = new javax.swing.JTextField();
        lblApellidoAlumno9 = new javax.swing.JLabel();
        lblNidAlumno12 = new javax.swing.JLabel();
        lblNidAlumno13 = new javax.swing.JLabel();
        txtGradoAlumno3 = new javax.swing.JTextField();
        btnAgregarAlumno3 = new javax.swing.JButton();
        btnBorrarAlumno3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnDocente = new javax.swing.JButton();
        btnAlumno = new javax.swing.JButton();
        btnAlumno1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 213, 225));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LOGO1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        LOGO1.setForeground(new java.awt.Color(255, 255, 255));
        LOGO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO1.setText("Area principal");
        LOGO1.setFocusable(false);
        LOGO1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGO1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpanDocente2.setBackground(new java.awt.Color(255, 255, 255));
        tpanDocente2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tpanDocente2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpnDocente.setBackground(new java.awt.Color(255, 255, 255));
        jpnDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tpanDocente1.setForeground(new java.awt.Color(0, 116, 208));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 111, 152));
        jLabel5.setText("Información del docente");

        lblCodigoAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno4.setText("Codigo");

        lblNombreAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno4.setText("Nombres");

        lblApellidoAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno4.setText("Apellidos");

        lblNidAlumno6.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno6.setText("NID");

        lblGeneroAlumno2.setForeground(new java.awt.Color(0, 116, 208));
        lblGeneroAlumno2.setText("Genero");

        lblFehcaNacAlumno2.setForeground(new java.awt.Color(0, 116, 208));
        lblFehcaNacAlumno2.setText("Fecha de nacimiento");

        DateDocente.setBackground(new java.awt.Color(0, 116, 208));
        DateDocente.setForeground(new java.awt.Color(0, 116, 208));
        DateDocente.setDateFormatString("yyyy-MM-dd");

        lblCodigoAlumno5.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno5.setText("Edad");

        txtEdadDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadDocenteActionPerformed(evt);
            }
        });

        lblNombreAlumno5.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno5.setText("Email");

        lblApellidoAlumno5.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno5.setText("Telefono");

        lblNidAlumno7.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno7.setText("Dirección");

        btnAgregarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/new_add_user_16734.png"))); // NOI18N
        btnAgregarDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBorrarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_cancel_128_28318.png"))); // NOI18N
        btnBorrarDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnActualizarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cloudrefresh_icon-icons.com_54403.png"))); // NOI18N
        btnActualizarDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSeleccionarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/emblemdefault_103452.png"))); // NOI18N
        btnSeleccionarDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addComponent(btnSeleccionarDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizarDocente)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarDocente)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarDocente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(lblFehcaNacAlumno2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DateDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(lblGeneroAlumno2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoAlumno5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdadDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreAlumno5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoAlumno5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNidAlumno7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lblCodigoAlumno4)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombreAlumno4)
                            .addComponent(txtNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoAlumno4)
                            .addComponent(txtApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNidAlumno6)
                            .addComponent(txtNidDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCodigoAlumno5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCodigoAlumno4)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAlumno4)
                    .addComponent(lblNombreAlumno5))
                .addGap(1, 1, 1)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoAlumno4)
                    .addComponent(lblApellidoAlumno5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNidAlumno6)
                    .addComponent(lblNidAlumno7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNidDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroAlumno2)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFehcaNacAlumno2)
                    .addComponent(DateDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnActualizarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarDocente, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnBorrarDocente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
        );

        tpanDocente1.addTab("Docente", jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpanDocente1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(tpanDocente1)
                .addContainerGap())
        );

        tblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Nombres", "Apellidos", "Nid", "Edad", "Email", "Telefono", "Dirección", "Genero", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDocente);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 111, 152));
        jLabel6.setText("Docentes");

        lblBuscarDocente.setBackground(new java.awt.Color(0, 111, 152));
        lblBuscarDocente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblBuscarDocente.setForeground(new java.awt.Color(0, 111, 152));
        lblBuscarDocente.setText("Buscar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lblBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblBuscarDocente)
                    .addComponent(txtBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnDocenteLayout = new javax.swing.GroupLayout(jpnDocente);
        jpnDocente.setLayout(jpnDocenteLayout);
        jpnDocenteLayout.setHorizontalGroup(
            jpnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDocenteLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDocenteLayout.setVerticalGroup(
            jpnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDocenteLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        tpanDocente2.addTab("Docentes", jpnDocente);

        jpnAlumno.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 111, 152));
        jLabel1.setText("Alumnos");

        lblBuscar.setBackground(new java.awt.Color(0, 111, 152));
        lblBuscar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(0, 111, 152));
        lblBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tpanAlumno1.setForeground(new java.awt.Color(0, 116, 208));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 111, 152));
        jLabel3.setText("Información del Alumno");

        lblCodigoAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno.setText("Codigo");

        lblNombreAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno.setText("Nombres");

        lblApellidoAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno.setText("Apellidos");

        lblNidAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno.setText("NID");

        lblGeneroAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblGeneroAlumno.setText("Genero");

        lblFehcaNacAlumno.setForeground(new java.awt.Color(0, 116, 208));
        lblFehcaNacAlumno.setText("Fecha de nacimiento");

        DateAlumno.setBackground(new java.awt.Color(0, 116, 208));
        DateAlumno.setForeground(new java.awt.Color(0, 116, 208));

        lblCodigoAlumno1.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno1.setText("Edad");

        txtEdaAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdaAlumnActionPerformed(evt);
            }
        });

        lblNombreAlumno1.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno1.setText("Email");

        lblApellidoAlumno1.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno1.setText("Telefono");

        lblNidAlumno1.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno1.setText("Dirección");

        lblNidAlumno2.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno2.setText("Grado");

        btnAgregarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/new_add_user_16734.png"))); // NOI18N
        btnAgregarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBorrarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_cancel_128_28318.png"))); // NOI18N
        btnBorrarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSeleccionarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/emblemdefault_103452.png"))); // NOI18N
        btnSeleccionarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnActualizaAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cloudrefresh_icon-icons.com_54403.png"))); // NOI18N
        btnActualizaAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbxGeneroAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(lblApellidoAlumno)
                                            .addGap(142, 142, 142))
                                        .addComponent(lblNombreAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombreAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigoAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCodigoAlumno)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNidAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblNidAlumno)
                                                    .addComponent(lblNidAlumno2)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(btnSeleccionarAlumno)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnActualizaAlumno))
                                                    .addComponent(txtGradoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreAlumno1)
                                    .addComponent(txtEdaAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigoAlumno1)
                                    .addComponent(txtEmailAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidoAlumno1)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDirecciondAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNidAlumno1)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(btnAgregarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarAlumno))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFehcaNacAlumno)
                                    .addComponent(lblGeneroAlumno))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxGeneroAlumno, 0, 134, Short.MAX_VALUE)
                                    .addComponent(DateAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoAlumno)
                            .addComponent(lblCodigoAlumno1))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdaAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreAlumno)
                            .addComponent(lblNombreAlumno1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoAlumno)
                            .addComponent(lblApellidoAlumno1))
                        .addGap(5, 5, 5)
                        .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNidAlumno1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblNidAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNidAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirecciondAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNidAlumno2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroAlumno)
                    .addComponent(cbxGeneroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFehcaNacAlumno)
                    .addComponent(DateAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccionarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        tpanAlumno1.addTab("Alumnos", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpanAlumno1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tpanAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Nombres", "Apellidos", "Nid", "Grado", "Edad", "Enail", "Telefono", "Dirección", "Genero", "Fecha de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        javax.swing.GroupLayout jpnAlumnoLayout = new javax.swing.GroupLayout(jpnAlumno);
        jpnAlumno.setLayout(jpnAlumnoLayout);
        jpnAlumnoLayout.setHorizontalGroup(
            jpnAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnAlumnoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );
        jpnAlumnoLayout.setVerticalGroup(
            jpnAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAlumnoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jpnAlumnoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tpanDocente2.addTab("Alumnos", jpnAlumno);

        jpnNota.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 111, 152));
        jLabel2.setText("Notas");

        lblBuscar1.setBackground(new java.awt.Color(0, 111, 152));
        lblBuscar1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblBuscar1.setForeground(new java.awt.Color(0, 111, 152));
        lblBuscar1.setText("Buscar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lblBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBuscar1)
                    .addComponent(txtBuscarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tpanAlumno4.setForeground(new java.awt.Color(0, 116, 208));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 111, 152));
        jLabel8.setText("Información del Alumno");

        lblCodigoAlumno8.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno8.setText("Codigo");

        lblNombreAlumno8.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno8.setText("Nombres");

        lblApellidoAlumno8.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno8.setText("Apellidos");

        lblNidAlumno11.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno11.setText("NID");

        lblGeneroAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        lblGeneroAlumno4.setText("Genero");

        rbtnGeneroMasAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        rbtnGeneroMasAlumno4.setText("Masculino");

        rbtnGeneroFemAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        rbtnGeneroFemAlumno4.setText("Femenino");

        lblFehcaNacAlumno4.setForeground(new java.awt.Color(0, 116, 208));
        lblFehcaNacAlumno4.setText("Fecha de nacimiento");

        DateAlumno4.setBackground(new java.awt.Color(0, 116, 208));
        DateAlumno4.setForeground(new java.awt.Color(0, 116, 208));

        lblCodigoAlumno9.setForeground(new java.awt.Color(0, 116, 208));
        lblCodigoAlumno9.setText("Edad");

        txtEdaAlumn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdaAlumn4ActionPerformed(evt);
            }
        });

        lblNombreAlumno9.setForeground(new java.awt.Color(0, 116, 208));
        lblNombreAlumno9.setText("Email");

        lblApellidoAlumno9.setForeground(new java.awt.Color(0, 116, 208));
        lblApellidoAlumno9.setText("Telefono");

        lblNidAlumno12.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno12.setText("Dirección");

        lblNidAlumno13.setForeground(new java.awt.Color(0, 116, 208));
        lblNidAlumno13.setText("Grado");

        btnAgregarAlumno3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/new_add_user_16734.png"))); // NOI18N
        btnAgregarAlumno3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBorrarAlumno3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_cancel_128_28318.png"))); // NOI18N
        btnBorrarAlumno3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addComponent(lblApellidoAlumno8)
                            .addGap(134, 134, 134))
                        .addComponent(lblNombreAlumno8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombreAlumno3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidoAlumno3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCodigoAlumn3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoAlumno8)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNidAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNidAlumno11)
                            .addComponent(lblNidAlumno13)
                            .addComponent(txtGradoAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAlumno9)
                            .addComponent(txtEdaAlumn4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoAlumno9)
                            .addComponent(txtEmailAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoAlumno9))
                        .addContainerGap())
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtDirecciondAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNidAlumno12))
                                .addGap(37, 77, Short.MAX_VALUE))))))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(lblGeneroAlumno4)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnGeneroMasAlumno4)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnGeneroFemAlumno4))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(lblFehcaNacAlumno4)
                                .addGap(18, 18, 18)
                                .addComponent(DateAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnAgregarAlumno3)
                                .addGap(49, 49, 49)
                                .addComponent(btnBorrarAlumno3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoAlumno8)
                            .addComponent(lblCodigoAlumno9))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoAlumn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdaAlumn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreAlumno8)
                            .addComponent(lblNombreAlumno9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoAlumno8)
                            .addComponent(lblApellidoAlumno9))
                        .addGap(5, 5, 5)
                        .addComponent(txtApellidoAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNidAlumno12))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblNidAlumno11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNidAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirecciondAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNidAlumno13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradoAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroAlumno4)
                    .addComponent(rbtnGeneroMasAlumno4)
                    .addComponent(rbtnGeneroFemAlumno4))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFehcaNacAlumno4)
                    .addComponent(DateAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarAlumno3)
                    .addComponent(btnBorrarAlumno3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpanAlumno4.addTab("Alumnos", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpanAlumno4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tpanAlumno4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblNotas);

        javax.swing.GroupLayout jpnNotaLayout = new javax.swing.GroupLayout(jpnNota);
        jpnNota.setLayout(jpnNotaLayout);
        jpnNotaLayout.setHorizontalGroup(
            jpnNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnNotaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4))
        );
        jpnNotaLayout.setVerticalGroup(
            jpnNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNotaLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tpanDocente2.addTab("Notas", jpnNota);

        btnDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/10219manteacherlightskintone_110630.png"))); // NOI18N
        btnDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        btnAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/130manstudent2_100617.png"))); // NOI18N
        btnAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });

        btnAlumno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/list_notes_930.png"))); // NOI18N
        btnAlumno1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumno1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpanDocente2)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDocente)
                    .addComponent(btnAlumno)
                    .addComponent(btnAlumno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tpanDocente2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadDocenteActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        // TODO add your handling code here:
        tpanDocente2.setSelectedIndex(0);
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
        // TODO add your handling code here
        tpanDocente2.setSelectedIndex(1);
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumno1ActionPerformed
        // TODO add your handling code here:
        tpanDocente2.setSelectedIndex(2);
    }//GEN-LAST:event_btnAlumno1ActionPerformed

    private void txtEdaAlumn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdaAlumn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdaAlumn4ActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Codigo Bonotes">
    private void txtEdaAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdaAlumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdaAlumnActionPerformed
    // </editor-fold> 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        Colegio usuarios = new Colegio();
        ControladorDocente D = new ControladorDocente(usuarios);
        ControladorAlumno A = new ControladorAlumno(usuarios);
        usuarios.setVisible(true);
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Colegio().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser DateAlumno;
    private com.toedter.calendar.JDateChooser DateAlumno4;
    public com.toedter.calendar.JDateChooser DateDocente;
    private javax.swing.JLabel LOGO1;
    public javax.swing.JButton btnActualizaAlumno;
    public javax.swing.JButton btnActualizarDocente;
    public javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnAgregarAlumno3;
    public javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnAlumno1;
    public javax.swing.JButton btnBorrarAlumno;
    private javax.swing.JButton btnBorrarAlumno3;
    public javax.swing.JButton btnBorrarDocente;
    private javax.swing.JButton btnDocente;
    public javax.swing.ButtonGroup btnGrupoDocente;
    public javax.swing.JButton btnSeleccionarAlumno;
    public javax.swing.JButton btnSeleccionarDocente;
    public javax.swing.ButtonGroup btngrupoAlumno;
    public javax.swing.JComboBox<String> cbxGenero;
    public javax.swing.JComboBox<String> cbxGeneroAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpnAlumno;
    private javax.swing.JPanel jpnDocente;
    private javax.swing.JPanel jpnNota;
    private javax.swing.JLabel lblApellidoAlumno;
    private javax.swing.JLabel lblApellidoAlumno1;
    private javax.swing.JLabel lblApellidoAlumno4;
    private javax.swing.JLabel lblApellidoAlumno5;
    private javax.swing.JLabel lblApellidoAlumno8;
    private javax.swing.JLabel lblApellidoAlumno9;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscar1;
    private javax.swing.JLabel lblBuscarDocente;
    private javax.swing.JLabel lblCodigoAlumno;
    private javax.swing.JLabel lblCodigoAlumno1;
    private javax.swing.JLabel lblCodigoAlumno4;
    private javax.swing.JLabel lblCodigoAlumno5;
    private javax.swing.JLabel lblCodigoAlumno8;
    private javax.swing.JLabel lblCodigoAlumno9;
    private javax.swing.JLabel lblFehcaNacAlumno;
    private javax.swing.JLabel lblFehcaNacAlumno2;
    private javax.swing.JLabel lblFehcaNacAlumno4;
    private javax.swing.JLabel lblGeneroAlumno;
    private javax.swing.JLabel lblGeneroAlumno2;
    private javax.swing.JLabel lblGeneroAlumno4;
    private javax.swing.JLabel lblNidAlumno;
    private javax.swing.JLabel lblNidAlumno1;
    private javax.swing.JLabel lblNidAlumno11;
    private javax.swing.JLabel lblNidAlumno12;
    private javax.swing.JLabel lblNidAlumno13;
    private javax.swing.JLabel lblNidAlumno2;
    private javax.swing.JLabel lblNidAlumno6;
    private javax.swing.JLabel lblNidAlumno7;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblNombreAlumno1;
    private javax.swing.JLabel lblNombreAlumno4;
    private javax.swing.JLabel lblNombreAlumno5;
    private javax.swing.JLabel lblNombreAlumno8;
    private javax.swing.JLabel lblNombreAlumno9;
    private javax.swing.JRadioButton rbtnGeneroFemAlumno4;
    private javax.swing.JRadioButton rbtnGeneroMasAlumno4;
    public javax.swing.JTable tblAlumnos;
    public javax.swing.JTable tblDocente;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTabbedPane tpanAlumno1;
    private javax.swing.JTabbedPane tpanAlumno4;
    private javax.swing.JTabbedPane tpanDocente1;
    private javax.swing.JTabbedPane tpanDocente2;
    public javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextField txtApellidoAlumno3;
    public javax.swing.JTextField txtApellidoDocente;
    private javax.swing.JTextField txtBuscarAlumno;
    private javax.swing.JTextField txtBuscarDocente;
    private javax.swing.JTextField txtBuscarNotas;
    public javax.swing.JTextField txtCodigoAlumn;
    private javax.swing.JTextField txtCodigoAlumn3;
    public javax.swing.JTextField txtCodigoDocente;
    public javax.swing.JTextField txtDireccionDocente;
    public javax.swing.JTextField txtDirecciondAlumno;
    private javax.swing.JTextField txtDirecciondAlumno4;
    public javax.swing.JTextField txtEdaAlumn;
    private javax.swing.JTextField txtEdaAlumn4;
    public javax.swing.JTextField txtEdadDocente;
    public javax.swing.JTextField txtEmailAlumno;
    private javax.swing.JTextField txtEmailAlumno4;
    public javax.swing.JTextField txtEmailDocente;
    public javax.swing.JTextField txtGradoAlumno;
    private javax.swing.JTextField txtGradoAlumno3;
    public javax.swing.JTextField txtNidAlumno;
    private javax.swing.JTextField txtNidAlumno3;
    public javax.swing.JTextField txtNidDocente;
    public javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreAlumno3;
    public javax.swing.JTextField txtNombreDocente;
    public javax.swing.JTextField txtTelefonoAlumno;
    private javax.swing.JTextField txtTelefonoAlumno4;
    public javax.swing.JTextField txtTelefonoDocente;
    // End of variables declaration//GEN-END:variables
}
